# Generated by Django 3.0.7 on 2020-06-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('email', models.CharField(max_length=220)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('date', models.DateField()),
                ('unit_type', models.CharField(max_length=50)),
                ('unit_space', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
